### ISSUE TITLE
你的规则无法添加

### ISSUE THREAD

**Issue by biange200** [TTDNS/Cat#5]
![Screenshot_20240807_111235.jpg](https://github.com/user-attachments/assets/eb01e8ee-e469-4ad9-8216-0a4750f6f264)

![Screenshot_20240807_111255.jpg](https://github.com/user-attachments/assets/d305b130-0a01-4539-a2dd-0b3e1d4188c0)
**https://raw.gitmirror.com/TTDNS/Cat/main/TT%E6%8B%92%E7%BB%9D%E5%88%97%E8%A1%A8%E6%B8%85%E5%8D%95%20(%E6%9B%B4%E6%96%B0%E4%B8%AD).txt**

**Comment by TTDNS** [comment]
> ![Screenshot_20240807_111235.jpg](https://private-user-images.githubusercontent.com/37582806/355662281-eb01e8ee-e469-4ad9-8216-0a4750f6f264.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NDY4MjYsIm5iZiI6MTcyOTY0NjUyNiwicGF0aCI6Ii8zNzU4MjgwNi8zNTU2NjIyODEtZWIwMWU4ZWUtZTQ2OS00YWQ5LTgyMTYtMGE0NzUwZjZmMjY0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDAxMjIwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwNGYwY2UyZjM3NDVmMTZiMDQ3ZTIwMTViYjljNGMyMTZhNmUwOTllNDM1NTNhNzJkMDdjY2ZhZmY3MWRiNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pCduXaEufNxyNYW3pMIrvmHaIy45nsTA_feY9iJ_OGo)
> 
> ![Screenshot_20240807_111255.jpg](https://private-user-images.githubusercontent.com/37582806/355662338-d305b130-0a01-4539-a2dd-0b3e1d4188c0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NDY4MjYsIm5iZiI6MTcyOTY0NjUyNiwicGF0aCI6Ii8zNzU4MjgwNi8zNTU2NjIzMzgtZDMwNWIxMzAtMGEwMS00NTM5LWEyZGQtMGIzZTFkNDE4OGMwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDAxMjIwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3ODZmZTBjNjc0ZTM2NGE5NTdlMzM1ZWUyNTRjZGNhZDQ2NGE3ZjFmOTM4OWNiNzIzN2Y3OTA3NGM1MTA2OTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.AK4L-QGPwNeMOB4yknq3R7Bv1F1rYqObgTiXgYF3-KI) **https://raw.gitmirror.com/TTDNS/Cat/main/TT%E6%8B%92%E7%BB%9D%E5%88%97%E8%A1%A8%E6%B8%85%E5%8D%95%20(%E6%9B%B4%E6%96%B0%E4%B8%AD).txt**

![Screenshot_20241023_092418](https://github.com/user-attachments/assets/5f2943e1-b2a8-491d-b570-6bffe677404e)
不存在该问题，重新点击保存就好

**Comment by TTDNS** [comment]
规则已更新，可以重新复制规则导入

**Comment by biange200** [comment]
> 规则已更新，可以重新复制规则导入

能增加domains通配符规则？不是adguard abp语法规则
可以支持invizible pro.personaldnsfilter的规则
